apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  
  labels:
    app: mysql
    tier: mysql
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        project: expense
    spec:
      containers:
      - name: nginx
        image: nisashap99/mysql-expense:1.0.0
        
